package consultorio;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class LoginSenha extends javax.swing.JFrame {
    // Members
    private String login = "";
    private String senha = "";
    private Banco b;
    private Connection con;
    private int role = 0;
    public static LoginSenha user;

    // getters and setters
    public int getRole(){return role;}
    public void setRole(int pRole)
    {
        this.role = pRole;
    }
    
    // Constructor
    public LoginSenha() {
        initComponents();

        // Initialize label Components
        lblErro.setVisible(false);
        lblSucesso.setVisible(false);
        
        // Get Connection with database
        b = new Banco();
        con = b.getConnection();
    }
    
    /**
     * This function checks login and password, and returns which role
     * is the user
     *
     * @param login
     * @param senha
     * @return 0 = Not found
     * @return 1 = Regular user
     * @return 2 = ADMIN user
     */
    private int Entrar(String login, String senha) throws SQLException
    {
        Statement comando = (Statement) this.con.createStatement();
        String queryString = "select L.LOGIN from clinica_psico.usuario L where L.LOGIN = ? and L.SENHA = MD5(?)";
        
        PreparedStatement query = (PreparedStatement) con.prepareStatement(queryString);
        query.setString(1, login);
        query.setString(2, senha);
        
        ResultSet resultado = query.executeQuery();
        while(resultado.next())
        {
            String resposta = resultado.getString("LOGIN");
            if ( resposta.equals("ADMIN"))
            {
                return 2;
            }
            else if (!resposta.equals("0"))
            {
                return 1;
            }
            else
            {
                return 0;
            }
        }
        return 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JToggleButton();
        lblErro = new javax.swing.JLabel();
        lblSucesso = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login");

        jLabel2.setText("Senha");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        btnEntrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblErro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErro.setForeground(new java.awt.Color(255, 0, 0));
        lblErro.setText("Erro na senha e/ou Login");

        lblSucesso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSucesso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSucesso.setText("Login feito com sucesso!");
        lblSucesso.setToolTipText("");

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblErro)
                    .addComponent(lblSucesso, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(lblErro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSucesso)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        
    }//GEN-LAST:event_txtLoginActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        this.login = txtLogin.getText();
        this.senha = txtSenha.getText();
        int lRole = 0;
        
        // Checks if the login and password are right(2 or 1) or wrong (0)
        try {
            lRole = this.Entrar(login, senha);
        } catch (SQLException ex) {
            Logger.getLogger(LoginSenha.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        if (this.senha.isEmpty() || this.txtLogin.getText().isEmpty() || lRole==0)
        {
            // If the password/login is wrong
            lblErro.setVisible(true);
            lblSucesso.setVisible(false);
            setRole(lRole);
        }
        else if(!this.senha.isEmpty() || !txtLogin.getText().isEmpty() || lRole>0)
        {
            // If the password/login is right
            lblErro.setVisible(false);
            lblSucesso.setVisible(true);
            setRole(lRole);
            this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblSucesso;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
